### ISSUE TITLE
Query result changes while iteration

### ISSUE THREAD

**Issue by sergiyha** [friflo/Friflo.Engine.ECS#24]
Hi. Please, don't ask me what the hell am I doing with this junk of code) This code represents the execution flow error. Maybe it is not an error and we cannot do things like that but anyway, I am here to show what I've found because it is strange.

The actual problem is that "Debug.LogError(_query.Chunks.Count + " Second Log");" shouldn't be executed twice but it is. Namely, if we do the same thing for a second time. As you can see "Debug.LogError(_query.Chunks.Count + " First Log");" is invoked only once.

FriFlo version: 2.0.0
Environment: Unity Editor 2022.3.47f1

```csharp
using Friflo.Engine.ECS;
using UnityEngine; 

public class Test : MonoBehaviour
{
	// Start is called before the first frame update
	void Start()
	{
		Exe();
	}

	public struct Comp_1 : IComponent
	{
	}

	public struct Comp_2 : IComponent
	{
	}

	public struct Comp_3 : IComponent
	{
	}

	public struct Comp_4 : IComponent
	{
	}


	public static void Exe()
	{
		var store = new EntityStore();
		var _query = store.Query<Comp_1>()
			.WithoutAllComponents(ComponentTypes.Get<Comp_2>());

		var cb = store.GetCommandBuffer();
		var brandNewEntt = store.CreateEntity();
		brandNewEntt.AddComponent<Comp_1>();
		cb.ReuseBuffer = true;
		
		foreach (var (c1, e) in _query.Chunks)
		{
			Debug.LogError(_query.Chunks.Count + " First Log");
			for (int i = 0; i < e.Length; i++)
			{
				var enttId = e[i];
				cb.AddComponent<Comp_2>(enttId);

				var newCB = store.GetCommandBuffer();
				newCB.AddComponent(enttId,new Comp_3());
				newCB.AddComponent(enttId, new Comp_4());
				newCB.Playback();
			}
		}
		cb.Playback();
		
		brandNewEntt.DeleteEntity();
		brandNewEntt = store.CreateEntity();
		brandNewEntt.AddComponent<Comp_1>();
		
		foreach (var (c1, e) in _query.Chunks)
		{
			Debug.LogError(_query.Chunks.Count + " Second Log");
			for (int i = 0; i < e.Length; i++)
			{
				var enttId = e[i];
				cb.AddComponent<Comp_2>(enttId);

				var newCB = store.GetCommandBuffer();
				newCB.AddComponent(enttId,new Comp_3());
				newCB.AddComponent(enttId, new Comp_4());
				newCB.Playback();
			}
		}

		cb.Playback();
	}
}
```
![image](https://github.com/user-attachments/assets/9cd7238a-3ae5-4627-8702-0f34105ca1fc)

**Comment by friflo** [comment]
Hi @sergiyha,

this query behavior is expected.
A query internally returns the chunks of all matching Archetypes.
The first loop has one the second loop has two matching Archetypes.
The second loop changes the Chunks of `_query.Archestypes[1]`.
See: https://github.com/friflo/Friflo.Engine.ECS/blob/main/src/Tests/ECS/Github/Test_GitHub_24.cs#L65

I added a possible fix at: https://github.com/friflo/Friflo.Engine.ECS/blob/main/src/Tests/ECS/Github/Test_GitHub_24.cs#L108

This version returns only the matching entities. This list is independent from Archetype changes.

**Comment by friflo** [comment]
Closed - see previous comment.

**Comment by sergiyha** [comment]
What is the reason for adding a new Archetype instead of replacing it?

**Comment by friflo** [comment]
Every Query stores (caches) an array of matching Archetypes.
When executing a query only new matching Archetypes created since last query execution are added to the query array.

This array grows only. This is done to improve query execution significant.
This schema is used to avoid iteration all Archetypes of an EntityStore to find matching Archetypes.

E.g. when executing the same query twice finding matching archetypes in the second query runs in O(1) in case no new Archetype was created between since the first query execution.

The number of archetypes in an EntityStore can grow very high (thousands) over time.
Using this schema the amortized time complexity to find matching archetypes is O(1).

A query iterates all matching Archetypes. A matching Archetype may have no entities. So a matching Archetype without entities cannot be replaced.

**Comment by sergiyha** [comment]
@friflo Thank you!
